// Run: node fetch-lpdb.js
// Requires: LPDB_KEY env var (apply at https://liquipedia.net/commons/Liquipedia:API_Usage_Guidelines)
// Writes updated data.js with live Elite Cup standings + player info.
//
// Usage:
//   LPDB_KEY=your_key node fetch-lpdb.js

import https from 'https';
import fs from 'fs';

const API_KEY = process.env.LPDB_KEY;
if (!API_KEY) { console.error('Set LPDB_KEY env var'); process.exit(1); }

const BASE = 'https://liquipediadb.org/api/v1';
const HEADERS = {
  'Authorization': `Apikey ${API_KEY}`,
  'User-Agent': 'road-to-riyadh/1.0 (angadkumar16ak@gmail.com)',
  'Accept': 'application/json',
};

function get(path) {
  return new Promise((resolve, reject) => {
    const url = BASE + path;
    https.get(url, { headers: HEADERS }, res => {
      let body = '';
      res.on('data', d => body += d);
      res.on('end', () => {
        if (res.statusCode !== 200) reject(new Error(`HTTP ${res.statusCode}: ${body}`));
        else resolve(JSON.parse(body));
      });
    }).on('error', reject);
  });
}

// Pause between requests to respect rate limits (60 req/hr = 1 per 60s; be safe)
function wait(ms) { return new Promise(r => setTimeout(r, ms)); }

async function main() {
  console.log('Fetching Elite Cup 2026 standings...');

  // ── 1. Standings ──────────────────────────────────────────────────────────
  // Adjust tournament name/id once you confirm exact LPDB identifier.
  // Common pattern: /trackmania/standings?tournament=Elite_Cup/2026
  const standings = await get('/trackmania/standings?tournament=Elite_Cup/2026&limit=64');
  console.log('Standings sample:', JSON.stringify(standings?.result?.[0], null, 2));

  await wait(2000);

  // ── 2. DreamHack Birmingham placements ───────────────────────────────────
  const dh = await get('/trackmania/placements?tournament=DreamHack/Birmingham/2026&limit=16');
  console.log('DH sample:', JSON.stringify(dh?.result?.[0], null, 2));

  const dhQualified = new Set(
    (dh?.result || []).filter(p => p.placement <= 8).map(p => p.player?.toLowerCase())
  );

  await wait(2000);

  // ── 3. Build player array ────────────────────────────────────────────────
  const rows = (standings?.result || []).map((entry, i) => {
    const tag  = entry.player || entry.name || '?';
    const nat  = entry.nationality || entry.country || null;
    const flag = nat ? countryToFlag(nat) : '?';
    const pts  = entry.points ?? null;
    const dh   = dhQualified.has(tag.toLowerCase());

    return {
      rank:    i + 1,
      tag,
      full:    entry.name_display || null,
      club:    entry.team || null,
      nat,
      flag,
      pts,
      dh,
      ewcEc:   false, // compute after
      enc:     false, // compute after
      cutline: false,
    };
  });

  // Mark cutline at rank 8 (top 8 non-DH get EWC · Elite Cup spot)
  const nonDh = rows.filter(r => !r.dh);
  nonDh.slice(0, 8).forEach(r => r.ewcEc = true);
  if (nonDh[7]) nonDh[7].cutline = true;

  // Mark ENC: first player per nation in top 16 (adjust threshold as needed)
  const seenNat = new Set();
  rows.slice(0, 16).forEach(r => {
    if (r.nat && !seenNat.has(r.nat)) { r.enc = true; seenNat.add(r.nat); }
  });

  // ── 4. Write data.js ─────────────────────────────────────────────────────
  const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  const lines = rows.map(r =>
    `  { rank:${String(r.rank).padEnd(2)} tag:${JSON.stringify(r.tag).padEnd(12)} full:${JSON.stringify(r.full).padEnd(28)} club:${JSON.stringify(r.club).padEnd(20)} nat:${JSON.stringify(r.nat).padEnd(6)} flag:${JSON.stringify(r.flag).padEnd(6)} pts:${JSON.stringify(r.pts).padEnd(6)} dh:${String(r.dh).padEnd(6)} ewcEc:${String(r.ewcEc).padEnd(6)} enc:${String(r.enc).padEnd(6)} cutline:${r.cutline} },`
  ).join('\n');

  const out = `// Auto-generated by fetch-lpdb.js — do not edit by hand.
// Run: LPDB_KEY=your_key node fetch-lpdb.js

const UPDATED = '${today}';

const players = [
${lines}
];
`;

  fs.writeFileSync('data.js', out);
  console.log(`data.js written — ${rows.length} players, updated ${today}`);
}

// ISO 3166-1 alpha-3 → emoji flag (covers common TM nations)
function countryToFlag(nat) {
  const map = {
    FRA:'🇫🇷', GBR:'🇬🇧', DEU:'🇩🇪', BEL:'🇧🇪', NLD:'🇳🇱',
    SWE:'🇸🇪', NOR:'🇳🇴', DNK:'🇩🇰', FIN:'🇫🇮', CAN:'🇨🇦',
    USA:'🇺🇸', BRA:'🇧🇷', AUS:'🇦🇺', POL:'🇵🇱', ESP:'🇪🇸',
    ITA:'🇮🇹', CHE:'🇨🇭', AUT:'🇦🇹', CZE:'🇨🇿', ROU:'🇷🇴',
    RUS:'🇷🇺', UKR:'🇺🇦', PRT:'🇵🇹', HUN:'🇭🇺', SVK:'🇸🇰',
  };
  return map[nat] || '?';
}

main().catch(e => { console.error(e.message); process.exit(1); });
